AllCops:
  Exclude:
    - "vendor/**/*"
  DisplayCopNames: true
  NewCops: disable
  TargetRubyVersion: 2.5
  SuggestExtensions: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/SignalException:
  EnforcedStyle: only_raise

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  Exclude:
    - "**/*.rake"
    - "Rakefile"

Layout/LineLength:
  Max: 160

Style/NumericLiterals:
  MinDigits: 7

Lint/AssignmentInCondition:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
