language: ruby
install: bundle install --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0-p647

gemfile:
  - Gemfile
  - activesupport.gemfile

addons:
  apt:
    packages:
    - memcached

before_install:
  - ntpdate -v ntp.nict.jp

script:
  - bundle exec rake spec
