language: ruby
install: bundle install --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
rvm:
  - 2.3.8

gemfile:
  - gemfiles/activesupport_5_2.gemfile

addons:
  apt:
    packages:
    - memcached

script:
  - bundle exec rake spec
