name: test

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - gemfiles/activesupport_5_2.gemfile
          - gemfiles/activesupport_6_0.gemfile
          - gemfiles/activesupport_6_1.gemfile
          - gemfiles/activesupport_7_0.gemfile
        exclude:
          - ruby: "2.5"
            gemfile: gemfiles/activesupport_7_0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/activesupport_7_0.gemfile
          - ruby: "3.0"
            gemfile: gemfiles/activesupport_5_2.gemfile
          - ruby: "3.0"
            gemfile: gemfiles/activesupport_5_2.gemfile
          - ruby: "3.1"
            gemfile: gemfiles/activesupport_5_2.gemfile
    services:
      memcached_11211:
        image: memcached
        ports:
          - 11211:11211
      memcached_21211:
        image: memcached
        ports:
          - 21211:11211
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec
